### ISSUE TITLE
PDF file as background

### ISSUE THREAD

**Issue by Johann150** [Johann150/neutron#10]
Allow the users to use a PDF file as background.

**Comment by Johann150** [comment]
maybe use [pdf-poppler](https://www.npmjs.com/package/pdf-poppler)

**Comment by jugendhacker** [comment]
Whats with the builtin PDF viewer of chromium?

**Comment by Johann150** [comment]
I did not think about that. But the problem is that the PDF has to be displayed in the background of the drawing canvas. And it is also necessary to get the PDF as an image for the "export as image" function.

**Comment by jugendhacker** [comment]
I dont know how the builtin viewer works so I cant say! But yes for the export you need to convert...

**Comment by Johann150** [comment]
The PDF import is working already. I implemented it as a special case for background images.
This way I won't have to adjust the "export as image" and saving functionality.

But one annoying thing remains: The conversion takes some time. So a loader would be nice. The nicest way would be a small dialog, but it seems there is none built into electron for this job. So it will probably be a css animation over the whole `<body>`.

**Comment by Johann150** [comment]
The page numbers in the image file names are zero padded, which causes some issues.

With 238d7edcc4c5ac7bbab4ade7c82f24b7d8580748 I tried to fix this behaviour. Although the images seem to be loaded correctly, there is an issues which have not found yet and no idea where to look.

**Comment by jugendhacker** [comment]
Whats the exact problem?

**Comment by Johann150** [comment]
When I have a PDF with >=10 pages, the images of the pages are correctly loaded but then not drawn correcly onto the canvas used to construct the background image. As a result, the call of `toDataUrl` (draw.js, l.505) returns a blank image.

**Comment by Johann150** [comment]
So I found [this](https://stackoverflow.com/questions/18865092/canvas-todataurl-returns-empty-canvas-size-is-not-zero/19135425#19135425) which seems to be the issue.

It states that the function does not work if the canvas is too big, which it probably is in this case because I have a canvas 35363px in height.

**Comment by Johann150** [comment]
If you have an idea, there will be. My only idea now would be maybe multiple background images. But I don't know how to implement that.

**Comment by jugendhacker** [comment]
Or just a "real" pdf view

**Comment by Johann150** [comment]
Well then there is the problem of saving it again...

**Comment by Johann150** [comment]
I give up.
I removed all the code in 722693c37d93695648b260d56ec8165826639852. It will just not be reliable enough to work with long documents too.
