### ISSUE TITLE
website german translation

### ISSUE THREAD

**Issue by Johann150** [Johann150/neutron#13]
Create an alternative website with a german translation.

The best solution would probably be separate folders: `/docs/en/` for the existing pages and `/docs/de/` for the german translation.

**Comment by jugendhacker** [comment]
Or you could do it with js...

**Comment by Johann150** [comment]
No, just a "stupid" translation this time.

**Comment by jugendhacker** [comment]
Ok, on Thursday I have time, so I could translate...
