### ISSUE TITLE
Autoupdate

### ISSUE THREAD

**Issue by jugendhacker** [Johann150/neutron#14]
I think something like this [autoupdater](https://blog.theodo.fr/2017/05/set-up-continuous-deployment-on-electron-using-squirrel/) would be a nice idea!

**Comment by Johann150** [comment]
Neutron is targeted at windows machines as a single executable file. Due to this, an autoupdater is not viable without delays on startup which would degrade user experience.

So it would generally be a good idea, but not for Neutron because of the way it is distributed.

**Comment by jugendhacker** [comment]
But it could show a window when a update is aviable and the user can click "Yes I want to install"

**Comment by Johann150** [comment]
True, but it would not make any sense in the way we presume it will be used: On a server in the schools network, read-only-access.
