### ISSUE TITLE
Agenda 2019

### ISSUE THREAD

**Issue by vonMitzscha** [Johann150/neutron#17]
There are some bugs that should be fixed in the next year (because of leaving the institution) and also some non-coding things that should be done in 2019:

- [x] **newly written text disappears after scrolling down or using the site-extension**
- [x] stupid features of the new Chrome version (like the scrolling with the pencil) should be prevented (maybe by using an old Chrome version?)
- [x] scrollbar is hard to use as it is too far in the corner
- [x] the flicker after an action should not happen anymore
- [x] replace the not used "background-feature" with a tool that displays a background grid
- [ ] a pull request for the "Electron Apps" [here](https://electronjs.org/apps)
- [x] new, adjusted documentation for Neutron
- [x] clarify the question of how to handle updates

_Altogether this ~last~ version should be stable and pre-tested by "our verified Beta-testers"_

**Comment by Johann150** [comment]
Using an older version of chrome (actually Electron) is definitely **NOT** an option.
Also: Seeing that we don't have an Idea where #11 comes from, it will be hard to fix.

**Comment by Johann150** [comment]
The grid is almost done with #18, there is still some UI cleanup to do before merging.

Something that will be answered later is how big the grid should be. Because this might be changed later, I used a CSS variable so it is easily changeable.

**Comment by Johann150** [comment]
regarding *the flicker after an action should not happen anymore*:  
Have you seen any flicker in the newer versions? Because I suspect that it also disappeared with the new canvas usage.

**Comment by vonMitzscha** [comment]
I think if the new neutron linkage is on all the blackboards, we can close this issue without a pull request at Electron. 
Maybe a wikie entry with a reference to how to create a link on the desktop would be useful (https://www.schieb.de/708965/internet-verknuepfungen-mit-verschiedenen-browsern-oeffnen).
