### ISSUE TITLE
Error with opening files

### ISSUE THREAD

**Issue by Johann150** [Johann150/neutron#6]
A bug we (me and @jugendhacker) found today: When opening a file, it only works if you have drawn something beforehand. The error seems to be that `activePath` is not correctly initialised.

I think @jugendhacker is working on that?

**Comment by jugendhacker** [comment]
Yes it's right I'm working on it! I think I'll finish it this afternoon!

**Comment by jugendhacker** [comment]
So this was a really little bug! I fixed it in just a few minutes!
